name: CLM LNRSUK PDEV Pipeline
on:
  workflow_dispatch:
    inputs: 
      release: 
        type: string
        description: RELEASE NUMBER
        required: true
        
jobs:
  web:
    name: Deploy LNRSUK PDEV [ RELEASE NO. ${{ github.event.inputs.release }} ]
    uses: LexisNexis-RBA/LexisNexis-CLM/.github/workflows/base-definition.yml@master
    with: 
      release: ${{ github.event.inputs.release }}
      prefix: lnrsuk-pdev
      aws_region: eu-west-2
      aws_account: ris-bussvcs-dev
      clm_fqdn: productdev-clm.eu.lnrm.net
      environment: pdev
      client: lnrsuk
    secrets: inherit
