name: CLM PNC CT Pipeline
on:
  workflow_dispatch:
    inputs: 
      release: 
        type: string
        description: RELEASE NUMBER
        required: true
        
jobs:
  web:
    name: Deploy PNC CT [ RELEASE NO. ${{ github.event.inputs.release }} ]
    uses: LexisNexis-RBA/LexisNexis-CLM/.github/workflows/base-definition.yml@master
    with: 
      release: ${{ github.event.inputs.release }}
      prefix: pnc-ct
      aws_region: us-east-2
      aws_account: ris-bussvcscustomercloud-prod
      clm_fqdn: test.pnc.clm.lexisnexisrisk.com
      environment: ct
      client: pnc
    secrets: inherit
